### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by olHz1** [Qiu-Jun/electron-vite-template#1]
打包环境：win10
开发时正常，但是build:win时，报配置错误。

**Comment by Qiu-Jun** [comment]
> 打包环境：win10 开发时正常，但是build:win时，报配置错误。

已处理。build的file配置导致

**Comment by olHz1** [comment]
> > 打包环境：win10 开发时正常，但是build:win时，报配置错误。
> 
> 已处理。build的file配置导致

十分感谢。最近也在学electron
